# Generated by Django 5.1.6 on 2025-06-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emergencyrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
