# Generated by Django 5.1.6 on 2025-06-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emergencyrequest_additional_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='matched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
